services:
  web:
    build: .
    ports:
      - "5005:5000"
    volumes:
      - .:/app
      - ./db:/app/db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000